name: Release
"on":
  push:
    branches:
      - master
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm clean-install
      - run: npm audit signatures
      - run: npx semantic-release@22.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
